
const questions = [
    {q:"Berapa sanksi maksimal untuk tindakan hacking (menembus sistem keamanan) menurut Pasal 30 ayat (3) UU ITE?",options:["6 tahun penjara dan/atau Rp 600 juta","7 tahun penjara dan/atau Rp 700 juta","8 tahun penjara dan/atau denda Rp 800 juta","12 tahun penjara dan/atau Rp 12 miliar"],answer:2,explanation:"Pasal 30(3) UU ITE: hacking level 3 (menembus keamanan) → maks 8 tahun / Rp 800 juta."},
    {q:"Pasal berapa dalam UU ITE yang melarang pembuatan, penjualan, dan distribusi perangkat/software yang khusus dirancang untuk kejahatan siber (seperti keylogger dan exploit kits)?",options:["Pasal 30","Pasal 32","Pasal 34","Pasal 36"],answer:2,explanation:"Pasal 34 mengkriminalisasi distribusi dan pemilikan tools cybercrime."},
    {q:"Apa perbedaan utama antara Policy (kebijakan) dan Law (hukum)?",options:["Keduanya identik, hanya beda istilah","Policy dibuat oleh pemerintah, law dibuat oleh perusahaan","Tidak tahu policy bisa jadi pembelaan yang sah, tetapi tidak tahu hukum BUKAN pembelaan yang sah","Policy sanksinya lebih berat dari hukum"],answer:2,explanation:"Ignorance of policy = acceptable defense, ignorance of law = NOT acceptable."},
    {q:"Dalam GDPR, ada 6 dasar hukum pemrosesan data pribadi. Manakah yang BUKAN termasuk dasar hukum tersebut?",options:["Consent (persetujuan eksplisit)","Legitimate interest (kepentingan yang sah)","Profit maximization (memaksimalkan keuntungan)","Vital interests (kepentingan vital)"],answer:2,explanation:"6 dasar GDPR: Consent, Contract, Legal, Vital, Public, Legitimate. Profit maximization bukan."},
    {q:"UU PDP mewajibkan pengendali data untuk memberikan notifikasi tertulis dalam berapa lama jika terjadi kebocoran data pribadi (data breach)?",options:["1 × 24 jam","3 × 24 jam","7 × 24 jam","14 × 24 jam"],answer:1,explanation:"UU PDP: notifikasi breach wajib dalam 3 × 24 jam kepada subjek data DAN otoritas pengawas."},
    {q:"Menurut UU PDP, data biometrik, catatan keuangan pribadi, dan data kesehatan tergolong ke dalam jenis data pribadi apa?",options:["Data Pribadi Umum (General)","Data Pribadi Spesifik (Specific)","Data Pribadi Terbatas (Restricted)","Data Pribadi Publik (Public)"],answer:1,explanation:"Data sensitif seperti biometrik, keuangan, kesehatan = Data Pribadi Spesifik menurut UU PDP."},
    {q:"Pasal 33 UU ITE melarang perbuatan yang membuat sistem elektronik tidak berfungsi sebagaimana mestinya. Contoh serangan yang tepat adalah...",options:["SQL Injection pada form login","Ransomware yang melumpuhkan server rumah sakit","Pencurian password via phishing","Pemalsuan dokumen elektronik"],answer:1,explanation:"Pasal 33 = gangguan sistem (DDoS, ransomware, malware yang merusak fungsi sistem)."},
    {q:"CFAA (Computer Fraud and Abuse Act) disebut sebagai 'cornerstone' hukum siber AS karena...",options:["Merupakan UU hak cipta tertua di AS","Merupakan fondasi utama (cornerstone) untuk banyak penegakan hukum federal terkait kejahatan komputer","Hanya berlaku untuk militer AS","Mengatur privasi data kesehatan"],answer:1,explanation:"CFAA adalah cornerstone (batu penjuru/fondasi) dari banyak hukum federal kejahatan komputer AS."},
    {q:"Seorang pentester melakukan pengujian kerentanan terhadap server perusahaan tanpa izin/kontrak, meskipun niatnya baik (white-hat). Menurut UU ITE, tindakan ini...",options:["Diperbolehkan karena niatnya baik","Tetap merupakan akses ilegal (Pasal 30), bahkan pentest tanpa consent = hacking","Hanya dikenakan peringatan lisan","Tidak diatur dalam UU ITE"],answer:1,explanation:"UU ITE Pasal 30: pentest tanpa izin = unauthorized access, terlepas niat baik/buruk."},
    {q:"Right to Erasure dalam GDPR (juga dikenal sebagai Right to be Forgotten) berarti...",options:["Hak untuk mengakses data","Hak untuk memindahkan data ke layanan lain","Hak untuk meminta penghapusan permanen data pribadi dari sistem","Hak untuk memperbaiki data yang salah"],answer:2,explanation:"Right to Erasure = hak meminta data pribadi dihapus permanen (right to be forgotten)."},
    {q:"4 tipe hukum yang harus dipahami adalah Civil, Criminal, Private, dan Public. Criminal Law secara khusus berfokus pada...",options:["Hubungan dan konflik antara organisasi dan individu","Aktivitas dan perilaku yang berbahaya bagi masyarakat, ditegakkan secara aktif oleh negara","Hubungan antar individu seperti keluarga dan tenaga kerja","Struktur dan administrasi lembaga pemerintah"],answer:1,explanation:"Criminal Law = menangani kejahatan yang berbahaya bagi masyarakat, ditegakkan oleh negara."},
    {q:"Organisasi (ISC)² memiliki 4 Canon dalam kode etiknya. Canon yang pertama dan paling utama adalah...",options:["Act honorably, honestly, justly","Provide diligent and competent service","Protect society, the common good, and the infrastructure","Advance and protect the profession"],answer:2,explanation:"Canon I (ISC)²: Protect society, the common good, and the infrastructure."},
    {q:"Peraturan BSSN No. 8 Tahun 2020 berfungsi sebagai...",options:["UU utama kejahatan siber di Indonesia","Standar teknis keamanan siber (baseline cybersecurity standard) untuk PSE di Indonesia","Peraturan khusus perlindungan hak cipta","Regulasi perbankan digital"],answer:1,explanation:"BSSN Reg 8/2020 = baseline cybersecurity standard, mewajibkan ISMS untuk PSE."},
    {q:"Sarbanes-Oxley Act (SOX) lahir sebagai respons terhadap skandal besar apa?",options:["Peretasan Sony Pictures","Skandal penipuan keuangan Enron","Kebocoran data Facebook-Cambridge Analytica","Serangan ransomware WannaCry"],answer:1,explanation:"SOX lahir dari skandal Enron fraud untuk meningkatkan akurasi pelaporan keuangan perusahaan publik."},
    {q:"Menurut UU No. 30 Tahun 2000, seorang programmer yang mencuri dan menjual algoritma rahasia perusahaannya ke kompetitor melanggar undang-undang tentang...",options:["Hak Cipta","Perlindungan Data Pribadi","Rahasia Dagang (Trade Secret)","Informasi dan Transaksi Elektronik"],answer:2,explanation:"UU 30/2000 = Rahasia Dagang. Algoritma rahasia = trade secret. Sanksi: 2 tahun / Rp 300 juta."},
    {q:"Dalam kode etik ACM, pilar 'Professional Responsibilities' mencakup prinsip...",options:["Protect society and common good","Strive for Quality, Respect Intellectual Property, Foster Public Awareness","Promote Ethical Decision-Making, Support Diversity","Uphold the Code and report unethical behavior"],answer:1,explanation:"ACM Professional Responsibilities: Quality, Respect IP, Foster Public Awareness."},
    {q:"Pasal 32 UU ITE mengkriminalisasi tindakan transfer, penyembunyian, atau penyebaran dokumen elektronik milik orang lain tanpa hak. Ini dikenal sebagai...",options:["Hacking","Intersepsi","Electronic Theft (Pencurian Elektronik)","Manipulasi Data"],answer:2,explanation:"Pasal 32 = Electronic Theft (pencurian/transfer dokumen elektronik tanpa hak)."},
    {q:"Perbedaan utama antara etika dan hukum dalam penegakannya adalah...",options:["Etika ditegakkan oleh pengadilan, hukum oleh komunitas","Hukum membawa otoritas pemerintah (memaksa), etika tidak memiliki otoritas pemerintah","Keduanya sama-sama ditegakkan oleh polisi","Etika memiliki sanksi lebih berat daripada hukum"],answer:1,explanation:"Laws carry the authority of a governing authority; ethics do not."},
    {q:"UU Hak Cipta No. 28 Tahun 2014 melindungi software/program komputer sebagai karya berhak cipta. Sanksi untuk pelanggaran hak cipta adalah...",options:["1 tahun penjara / Rp 100 juta","2 tahun penjara / Rp 300 juta","4 tahun penjara / Rp 1 miliar","12 tahun penjara / Rp 12 miliar"],answer:2,explanation:"UU 28/2014 Hak Cipta: sanksi maks 4 tahun / Rp 1 miliar."},
    {q:"Economic Espionage Act (EEA) 1996 di AS secara khusus mengkriminalisasi...",options:["Pembajakan software dan film","Pencurian atau penyalahgunaan rahasia dagang (trade secrets) untuk kepentingan pemerintah atau entitas asing","Penyadapan komunikasi telepon","Pelanggaran privasi data kesehatan"],answer:1,explanation:"EEA mengkriminalisasi pencurian trade secrets yang dimaksudkan untuk menguntungkan pemerintah/entitas asing."}
];

function renderQuiz(){const c=document.getElementById('quizContainer');const s=JSON.parse(localStorage.getItem('pkpl_quiz_ch06_answers')||'{}');c.innerHTML=questions.map((q,i)=>`<div class="quiz-question" id="qq-${i}"><div class="q-num">Soal ${i+1} dari ${questions.length}</div><div class="q-text">${q.q}</div>${q.options.map((opt,j)=>`<label class="quiz-option" id="opt-${i}-${j}"><input type="radio" name="q${i}" value="${j}" ${s[i]==j?'checked':''} onchange="saveAnswer(${i},${j})"><span>${opt}</span></label>`).join('')}</div>`).join('')}
function saveAnswer(qi,oi){const s=JSON.parse(localStorage.getItem('pkpl_quiz_ch06_answers')||'{}');s[qi]=oi;localStorage.setItem('pkpl_quiz_ch06_answers',JSON.stringify(s))}
function submitQuiz(){const saved=JSON.parse(localStorage.getItem('pkpl_quiz_ch06_answers')||'{}');let correct=0;questions.forEach((q,i)=>{q.options.forEach((_,j)=>{const el=document.getElementById(`opt-${i}-${j}`);el.classList.remove('correct','incorrect');const old=el.querySelector('.explanation');if(old)old.remove()});const ua=saved[i];if(ua!==undefined){if(parseInt(ua)===q.answer){correct++;document.getElementById(`opt-${i}-${q.answer}`).classList.add('correct')}else{document.getElementById(`opt-${i}-${ua}`).classList.add('incorrect');document.getElementById(`opt-${i}-${q.answer}`).classList.add('correct')}}else{document.getElementById(`opt-${i}-${q.answer}`).classList.add('correct')}const expDiv=document.createElement('div');expDiv.className='explanation';expDiv.style.display='block';expDiv.textContent='💡 '+q.explanation;document.getElementById(`opt-${i}-${q.answer}`).appendChild(expDiv)});const rb=document.getElementById('resultBox');rb.style.display='block';document.getElementById('scoreText').textContent=`${correct}/${questions.length}`;const pct=Math.round((correct/questions.length)*100);document.getElementById('scoreMessage').textContent=pct>=80?'🎉 Luar biasa! Materi Law & Ethics sudah dikuasai!':pct>=60?'👍 Bagus! Review lagi pasal-pasal UU ITE ya!':'📚 Hapalkan pasal UU ITE dan perbedaan etika vs hukum!';localStorage.setItem('pkpl_quiz_ch06',JSON.stringify({correct,total:questions.length}));rb.scrollIntoView({behavior:'smooth'})}
function resetQuiz(){localStorage.removeItem('pkpl_quiz_ch06_answers');localStorage.removeItem('pkpl_quiz_ch06');document.getElementById('resultBox').style.display='none';renderQuiz()}
renderQuiz();
